In [16]:
import numpy
import scipy.special

In [22]:


class NeuralNetworks: 
        def __init__(self, inodes, hnodes, onodes, learning_rate) -> None:
                self.input_nodes = inodes
                self.hidden_nodes = hnodes
                self.output_nodes = onodes
                self.learning_rate = learning_rate
                self.input_hidden_weights = numpy.random.normal(0.0, pow(self.hidden_nodes, -0.5), (self.hidden_nodes, self.input_nodes))
                self.hidden_output_weights = numpy.random.normal(0.0, pow(self.output_nodes, -0.5), (self.output_nodes, self.hidden_nodes) )
                self.activation_function = lambda x: scipy.special.expit(x)
                pass
        
        def train(self, inputlist, traininglist):
                 (initial_output, initial_hidden, initial_input) = self.query(inputlist)
                 eoutput = numpy.array(traininglist, ndmin=2).T - initial_output
                 ehidden = numpy.dot(self.hidden_output_weights.T, eoutput)
                 change_in_hidden_output_weights = self.learning_rate * numpy.dot(eoutput * initial_output * (1 - initial_output) , initial_hidden.T)
                 change_in_input_hidden_weights = self.learning_rate * numpy.dot(ehidden * initial_hidden * (1 - initial_hidden) , initial_input.T)
                 self.hidden_output_weights = self.hidden_output_weights + change_in_hidden_output_weights
                 self.input_hidden_weights = self.input_hidden_weights + change_in_input_hidden_weights
                 pass
        
        def query(self, input):
                 inputs = numpy.array(input, ndmin = 2).T
                 hidden_inputs = numpy.dot(self.input_hidden_weights, inputs)
                 hidden_outputs = self.activation_function(hidden_inputs)
                 final_inputs = numpy.dot(self.hidden_output_weights, hidden_outputs)
                 final_outputs = self.activation_function(final_inputs)
                 return (final_outputs, hidden_outputs, inputs)



In [23]:
input_nodes = 3
hidden_nodes = 3
output_nodes = 3
learning_rate = 0.3
sample_input = [1.0, 0.5, 1.5]
n = NeuralNetworks(input_nodes, hidden_nodes, output_nodes, learning_rate)
n.query(sample_input)

(array([[0.47118406],
        [0.34716518],
        [0.40444559]]),
 array([[0.54460554],
        [0.35848307],
        [0.57374081]]),
 array([[1. ],
        [0.5],
        [1.5]]))

In [ ]:
n.train([1.0, 0.5, 1.5], [0.5, 0.3, 2.1] )